version: "3"

services:

  php:
    image: nbcwebcontainers.azurecr.io/appservice-drupal-php:7.x-7.2
    environment:
      SOLR_HEAP: 1024m
      WEBSITES_PORT: 8080
    volumes:
      - ./data:/home
    ports:
      - "8080:8080"
      - "2222:2222"
